In [1]:
import os
os.chdir("..")

In [2]:
from src import Trainer
from src.agents import QLearning
import torch
from torch import nn

In [18]:
with open('configs/colour-grid/agent.yaml') as f:
    trainer = Trainer.from_yaml(f)
print(trainer)

In [19]:
trainer.train()

wandb: WARNING When using several event log directories, please call `wandb.tensorboard.patch(root_logdir="...")` before `wandb.init`


AttributeError: 'tuple' object has no attribute 'copy'

In [11]:
agent: QLearning = trainer.objective
print(dict(agent.Q_table))

{(0, 0): array([5., 6., 5., 5.]), (1, 0): array([7., 6., 6., 5.]), (1, 1): array([8., 7., 6., 7.]), (1, 2): array([9.        , 8.        , 7.        , 7.99928236]), (1, 3): array([6.28594535, 6.5509102 , 6.22968548, 6.25014068]), (0, 2): array([8.99993423, 8.        , 6.58111717, 5.46162486]), (0, 3): array([0.        , 1.2       , 2.52      , 6.65511481])}


In [ ]:
with open('configs/colour-grid/pc.yaml') as f:
    pctrainer = Trainer.from_yaml(f)

In [4]:
pctrainer.train()

wandb: Currently logged in as: ben2508 (ben2508-projects) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.


 11%|█         | 44/400 [06:57<56:16,  9.48s/it]  


KeyboardInterrupt: 

wandb: WARNING Fatal error while uploading data. Some run data will not be synced, but it will still be written to disk. Use `wandb sync` at the end of the run to try uploading.


In [5]:
from src.sverl import Characteristic
from src import Trainable
cf: Characteristic = Trainable.load_checkpoint('checkpoints/grid-pc/40.pt')

In [17]:
steady_state = [[0, 0], [1, 0], [1, 1], [1, 2], [-100, -100], [-100, 0], [0, -100], [1, -100], [-100, 1], [-100, 2]]
for state in steady_state:
    v = cf.infer(torch.Tensor(state).unsqueeze(0).to(cf.device)).round(decimals=2)
    print(v)

tensor([[0., 1., 0., 0.]], device='cuda:0')
tensor([[1., 0., 0., 0.]], device='cuda:0')
tensor([[1., 0., 0., 0.]], device='cuda:0')
tensor([[1., 0., 0., 0.]], device='cuda:0')
tensor([[0.8800, 0.1200, 0.0000, 0.0000]], device='cuda:0')
tensor([[0.6500, 0.3500, 0.0000, 0.0000]], device='cuda:0')
tensor([[0., 1., 0., 0.]], device='cuda:0')
tensor([[1., 0., 0., 0.]], device='cuda:0')
tensor([[1., 0., 0., 0.]], device='cuda:0')
tensor([[1., 0., 0., 0.]], device='cuda:0')
